version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: videogames
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: "exit 0"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306 

  web:
    image: php:7.4-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  db_data:
